### ISSUE TITLE
Callback parameter 'text' returns an array instead of a string

### ISSUE THREAD

**Issue by Anthromada** [AlexzanderFlores/WOKCommands#20]

**Comment by AlexzanderFlores** [comment]
Hey, for version 1.1.9 and above you should be able to destructure your "args" array instead of using multiple parameters in your callback methods.

See the new documentation for more details: https://www.npmjs.com/package/wokcommands#creating-a-command
Video change log: (4:42 long) https://www.youtube.com/watch?v=vDYiMVMnhfY
